# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45a793029fc6cbfb7ce9f69ff1380c9cded01878e2f8ee79a6a230790e4ff84b075077e49e2e2d6b216060628c1017ab5c8ffb2ffb2b4eb25f345eda3942d0d4

test:
  secret_key_base: 86942ba2cfe12715084a653ca294303161cd9279cda3ee2f7eaf5b3d12f7e1c3dd9ec33252b00c8fe7ec762ad613a4173e9f0e3c2165b6c773d8c0ec47f5ddb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
